app = "recircle-backend"
primary_region = "bom"

[build]
  [build.args]
    JWT_SECRET = "reCircleSecretKey2024ForHackathonProjectSecure"
    JWT_EXPIRATION = "86400000"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  JWT_SECRET = "reCircleSecretKey2024ForHackathonProjectSecure"
  JWT_EXPIRATION = "86400000"
